_wandb:
    value:
        cli_version: 0.20.1
        m:
            - "1": epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "1": val_fss_3
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_fss_5
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_fss_9
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": val_auc
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_epoch
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": train_loss_step
              "5": 2
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 9
                - 41
                - 103
            "2":
                - 1
                - 9
                - 41
                - 103
            "3":
                - 7
                - 13
                - 55
                - 66
            "4": 3.12.2
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
dropout_p:
    value: 0.2
embed_dim:
    value: 128
lr:
    value: 0.0001
num_heads:
    value: 4
num_layers:
    value: 4
out_hw:
    value:
        - 350
        - 370
